ERROR:utils.evaluator:Cannot work out file type of "/"
Traceback (most recent call last):
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 352, in evaluate2view
    device)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 159, in _segment_vol
    orientation=orientation)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/data_utils.py", line 96, in load_and_preprocess_eval
    volume_nifty = nb.load(file_path[0])
  File "/home/sabs-r3/anaconda3/envs/GE_GUI/lib/python3.7/site-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/"
ERROR:utils.evaluator:Cannot work out file type of "/"
Traceback (most recent call last):
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 352, in evaluate2view
    device)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 159, in _segment_vol
    orientation=orientation)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/data_utils.py", line 96, in load_and_preprocess_eval
    volume_nifty = nb.load(file_path[0])
  File "/home/sabs-r3/anaconda3/envs/GE_GUI/lib/python3.7/site-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/"
ERROR:utils.evaluator:Cannot work out file type of "/"
Traceback (most recent call last):
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 353, in evaluate2view
    device)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 159, in _segment_vol
    orientation=orientation)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/data_utils.py", line 96, in load_and_preprocess_eval
    volume_nifty = nb.load(file_path[0])
  File "/home/sabs-r3/anaconda3/envs/GE_GUI/lib/python3.7/site-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/"
ERROR:utils.evaluator:Cannot work out file type of "/"
Traceback (most recent call last):
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 353, in evaluate2view
    device)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 159, in _segment_vol
    orientation=orientation)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/data_utils.py", line 96, in load_and_preprocess_eval
    volume_nifty = nb.load(file_path[0])
  File "/home/sabs-r3/anaconda3/envs/GE_GUI/lib/python3.7/site-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/"
ERROR:utils.evaluator:Cannot work out file type of "/"
Traceback (most recent call last):
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 353, in evaluate2view
    device)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/evaluator.py", line 159, in _segment_vol
    orientation=orientation)
  File "/home/sabs-r3/Desktop/GE/quickNAT_pythorch/utils/data_utils.py", line 96, in load_and_preprocess_eval
    volume_nifty = nb.load(file_path[0])
  File "/home/sabs-r3/anaconda3/envs/GE_GUI/lib/python3.7/site-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/"
